services:
  adguardhome-sync:
    hostname: adguardhome
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    ports:
      - 30230:8080
    environment:
      - PUID=200
      - PGID=100
      - TZ=Europe/Moscow
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /srv/docker/adguardhome/assets/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    networks:
      net:
        ipv4_address: 198.19.2.3
    depends_on:
       - adguardhome
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
