version: 3.7

networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.2.0/24
          gateway: 198.19.2.1

#volumes:
#  work:
#  conf:

services:
  adguard:
    container_name: adguardhome
    hostname: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - ${HOSTIP}:53:53/udp
      - 30220:80/tcp
      - 30224:443
      - 30221:3000/tcp
      - 853:853
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /srv/docker/adguardhome/storage/work:/opt/adguardhome/work
      - /srv/docker/adguardhome/storage/conf:/opt/adguardhome/conf
    networks:
      net:
        ipv4_address: 198.19.2.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  adguardhome-sync:
    hostname: adguardhome
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    ports:
      - 30230:8080
    environment:
      - PUID=200
      - PGID=100
      - TZ=Europe/Moscow
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /srv/docker/adguardhome/assets/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    networks:
      net:
        ipv4_address: 198.19.2.3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    condition: env_var:ISSLAVE=true
    restart: unless-stopped
