networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.14.0/24
          gateway: 198.19.14.1

volumes:
    data:
    meilisearch:

services:
    karakeep:
        container_name: karakeep
        image: ghcr.io/karakeep-app/karakeep:release
        hostname: web
        volumes:
            - data:/data
        ports:
            - 31420:3000
        env_file:
            - /srv/docker/enviroments/karakeep.env
        environment:
            - MEILI_ADDR=http://meilisearch:7700
            - BROWSER_WEB_URL=http://chrome:9222
            - DATA_DIR=/data
            - NEXTAUTH_URL=http://localhost:3000
            - DISABLE_SIGNUPS=true
        networks:
            net:
                ipv4_address: 198.19.14.2
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"
        restart: unless-stopped

    chrome:
        container_name: karakeep-chrome
        image: gcr.io/zenika-hub/alpine-chrome:123
        hostname: chrome
        command:
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
        networks:
            net:
                ipv4_address: 198.19.14.3
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"
        restart: unless-stopped

    meilisearch:
        container_name: karakeep-meilisearch
        image: getmeili/meilisearch:v1.13.3
        hostname: meilisearch
        env_file:
            - /srv/docker/enviroments/karakeep.env
        environment:
            - MEILI_NO_ANALYTICS=true
        volumes:
            - meilisearch:/meili_data
        networks:
            net:
                ipv4_address: 198.19.14.4
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"
        restart: unless-stopped
  