networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.14.0/24
          gateway: 198.19.14.1

volumes:
  config:

services:
  radarr:
    container_name: radarr
    hostname: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 31420:7878
    volumes:
      - config:/config
      - /mnt/local-media/Video/Movies:/video/movies
      - /mnt/local-media/Video/Animation:/video/animation
      - /mnt/local-load/Download/Torrent:/downloads
    environment:
      - PUID=200
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK=002
    networks:
      net:
        ipv4_address: 198.19.14.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
