networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.3.0/24
          gateway: 198.19.3.1

volumes:
  data:
  letsencrypt:

services:
  nginxproxymanager:
    container_name: nginxproxymanager
    hostname: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 30320:81
      - 80:80
      - 443:443
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      net:
        ipv4_address: 198.19.3.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped