networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.8.0/24
          gateway: 198.19.8.1

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 7 * * 6
      - WATCHTOWER_ROLLING_RESTART=true
    networks:
      net:
        ipv4_address: 198.19.8.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: always