networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.6.0/24
          gateway: 198.19.6.1

volumes:
  config:

services:
  qbittorrent:
    container_name: qbittorrent
    hostname: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK=002
      - WEBUI_PORT=80
    volumes:
      - config:/config
      - ${DATA_DOWNLOAD}:/downloads/unsorted
    ports:
      - 30620:80
      - 6881:6881
      - 6881:6881/udp
    networks:
      net:
        ipv4_address: 198.19.6.2
    healthcheck:
        test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.6.2:80"]
        interval: 30s
        timeout: 10s
        start_period: 10s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped