networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.12.0/24
          gateway: 198.19.12.1

volumes:
  config:

services:
  calibre-web:
    container_name: calibreweb
    hostname: calibreweb
    image: lscr.io/linuxserver/calibre-web:latest
    ports:
      - 31220:8083
    environment:
      - TZ=Europe/Moscow
      - PUID=1999
      - PGID=100
      - UMASK=002
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - config:/config
      - /var/snap/docker/common/assets/calibreweb/xdg-desktop-menu:/usr/bin/xdg-desktop-menu:ro
      - /var/snap/docker/common/assets/calibreweb/xdg-icon-resource:/usr/bin/xdg-icon-resource:ro
      - /var/snap/docker/common/assets/calibreweb/xdg-mime:/usr/bin/xdg-mime:ro
      - ${DATA_BOOKS}:/books
    networks:
      net:
        ipv4_address: 198.19.12.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.12.2:8083"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped