networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.15.0/24
          gateway: 198.19.15.1

volumes:
  data:
  config:

services:
  semaphore:
    container_name: semaphore
    hostname: semaphore
    image: public.ecr.aws/semaphore/pro/server
    ports:
      - 31520:3000
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=Admin
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
    volumes:
      - data:/var/lib/semaphore
      - config:/etc/semaphore
    networks:
      net:
        ipv4_address: 198.19.15.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: always

#    healthcheck:
#        test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.5.2:3000"]
#        interval: 30s
#        timeout: 10s
#        retries: 3
