networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.18.0/24
          gateway: 198.19.18.1

services:
  torproxy:
    container_name: torproxy
    hostname: torproxy
    image: zerolabnet/tor-bridges-proxy:latest
    volumes:
#      - /var/snap/docker/common/assets/torproxy/torrc:/etc/tor/torrc
      - /var/snap/docker/common/assets/torproxy/bridges.txt:/etc/tor/bridges.txt
    ports:
      - 31820:9151/tcp
      - 31821:9150/tcp
    networks:
      net:
        ipv4_address: 198.19.18.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped