networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.13.0/24
          gateway: 198.19.13.1

volumes:
  config:
#  proxy_config:
#  lostfilm_config:
  
services:
  jackett:
    container_name: jackett
    hostname: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - 31320:9117
    volumes:
      - config:/config
      - /srv/docker/injections/jackett/noname-clubl-rus.yml:/app/Jackett/Definitions/noname-clubl-rus.yml:ro
    environment:
      - PUID=200
      - PGID=100
      - TZ=Europe/Moscow
    networks:
      net:
        ipv4_address: 198.19.13.2
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
#    depends_on:
#      - flaresolverr

#  flaresolverr:
#    image: ghcr.io/flaresolverr/flaresolverr:latest
#    container_name: jackett-flaresolverr
#    hostname: flaresolverr
#    networks:
#      net:
#        ipv4_address: 198.19.13.3
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "2m"
#        max-file: "10"
#    restart: unless-stopped

