volumes:
  config:

services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    network_mode: host
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
    volumes:
      - config:/config
      - /var/run/dbus:/var/run/dbus:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8123:8123
    healthcheck:
        test: ["CMD", "wget", "--spider", "--timeout=10", "http://localhost:8123"]
        interval: 30s
        timeout: 10s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped